### ISSUE TITLE
Data collected inside DB but not shown on GUI 

### ISSUE THREAD

**Issue by michelep** [sipcapture/homer-installer#13]
Hi all, i've installed Homer 5 on a vanilla Debian 8 using provided script. After configuring siptrace on my OpenSIPS server, Homer MySQL DB was populated with VoIP datas *but* on GUI frontend, after login, i cant' see any data/nothing. Just a "No Data Available.".

Any hint ?

Michele

**Comment by giavac** [comment]
Hi Michele,
please double check the Time Range (top right) and ensure it's consistent with the data you have in the DB.

If it is, e.g. it refers to a time range that has data in the DB, then you could trace the activity on port 3306 and verify the queries from the GUI are correctly received by the DB, and what responses or errors are provided by the DB.

Giacomo

**Comment by michelep** [comment]
IT WORKS ! Thanks, i didn't see time range in the top left of the frontend: correctly setting of datetime fix the problem and now i can see voip traffic data.

Thanks a lot.

Michele

**Comment by giavac** [comment]
You're welcome Michele.
Enjoy Homer!

Giacomo
