### ISSUE TITLE
Duplicate entry '1' for key 'PRIMARY' error when install HOMER through script

### ISSUE THREAD

**Issue by yuqian08** [sipcapture/homer-installer#16]
here is the full log, i am use Debian8, and followed the homer-installer, but always got this error
Patching Homer configuration...
Can't open /opt/homer_rotate: No such file or directory.
Can't open /opt/homer_rotate: No such file or directory.
chmod: cannot access ‘/opt/homer_rotate’: No such file or directory
chmod: cannot access ‘/opt/homer_rotate’: No such file or directory
Can't open /opt/homer_rotate: No such file or directory.
Can't open /opt/homer_rotate: No such file or directory.
Restarting apache2 (via systemctl): apache2.service.
Restarting kamailio (via systemctl): kamailio.serviceJob for kamailio.service failed. See 'systemctl status kamailio.service' and 'journalctl -xn' for details.
 failed!

**Comment by lmangani** [comment]
Could you confirm if the folder ```/usr/src/homer-api/scripts/mysql/``` exists and its contents please?

**Comment by lmangani** [comment]
Patch pushed, could you kindly re-test if the issue is addressed?

**Comment by 00Asgaroth00** [comment]
This issue is corrected in pull request #23
