### ISSUE TITLE
Kamailio starts up before mysql service causing service to fail at bootup

### ISSUE THREAD

**Issue by dig12345** [sipcapture/homer-installer#28]
need to add a systemd unit file to add dependency on mysql service. stock kamailio does not require this:
mkdir /etc/systemd/system/kamailio.service.d/
nano /etc/systemd/system/kamailio.service.d/kamailio.conf

[Unit]
After= mysql.service

**Comment by 00Asgaroth00** [comment]
Hi, I'm guessing the systemd configuration file should really be living with the rest of the service definitions in /lib/systemd/system/kamailio.service.d/. I'll take a look at this.

BTW, which distro you running this on? Is it Debian 8 or CentOS 7?

**Comment by dig12345** [comment]
No. If you add it to the regular location it will get overwitten by any package updates to kamailio. I've been down that road before. 
This is on Debian 8.
I suspect this issue plagues many new users and they just give up. It strikes only after the first reboot and is likely inconsistent based on startup times.

**Comment by 00Asgaroth00** [comment]
This should be addressed now.
