### ISSUE TITLE
Typo in path to $WEBROOT/api/preferences.php

### ISSUE THREAD

**Issue by mbeckwell** [sipcapture/homer-installer#3]
On the main homer_installer.sh script, at approximately line 571, the path to the preferences.php appears to have a typo on it:

Currently is:
echo "         '$WEBROOT/a[o/preferences.php'"

I believe it should be:
echo "         '$WEBROOT/api/preferences.php'"

**Comment by lmangani** [comment]
Thanks for flagging this @mbeckwell 
Fixed in a93b2b92e6297e0e59d33263ee9afdc398f5d249
