### ISSUE TITLE
add homer_rotate to startup

### ISSUE THREAD

**Issue by dig12345** [sipcapture/homer-installer#30]
Does it make sense to add homer_rotate to etc/init.d for the case where a machine has been sleeping for more than 3 days. Otherwise the tables are not there and INSERTS fail until next cron job time. I had this situation when launching a homer instance from image.

**Comment by 00Asgaroth00** [comment]
In my opinion, I think that is very specific, I would expect a homer system to rarely, if ever, be in a sleep state, rather, it would be up capturing traffic all the time. I think, in an edge case, like yours, it should be up to the sysadmin of the system to add facilities to remedy the edge cases.
