### ISSUE TITLE
Debian 9 Stretch support

### ISSUE THREAD

**Issue by ludovic-gasc** [sipcapture/homer-installer#34]
I open an issue as requested by Lorenzo Mangani: https://groups.google.com/forum/#!topic/homer-discuss/h3wcCmEV19c

BTW, thanks for your awesome job ;-)

**Comment by negbie** [comment]
Should be no problem but for now we would have to use 5.0nightly 	if this is up to date. https://www.kamailio.org/wiki/packages/debs

**Comment by negbie** [comment]
Otherwise we can build it from src but it would take some extra time during the installation

**Comment by SipSeb** [comment]
Actually, there are Stretch packages, but only for the /kamailio50 repository. The /kamailio repository doesn't have them. I must have missed that when updating the Wiki page lately. Fixed it just now.

Maybe @linuxmaniac can add Stretch packages in the /kamailio repository for the upcoming 5.0.3 release, too.

**Comment by negbie** [comment]
Thanks for the info Sebastian. @GMLudo could you try the stretch-kamailio-5.x branch?
git clone https://github.com/sipcapture/homer-installer.git -b stretch-kamailio-5.x

**Comment by negbie** [comment]
On a minimal Debian Stretch image you first need to install dirmngr and lsb-release.

PS:
When you have some time and want to help us you can put all this changes into the base installer script by simply adding some new switch case for debian 9. I was to lazy to do this ;)
