### ISSUE TITLE
not getting data at sip signaling

### ISSUE THREAD

**Issue by prashantvidja** [sipcapture/homer-installer#35]
Hello

I am not getting data at sip signaling...
but in sip_capture table I getting all entry of my all CDRS of calls
so something issue at sip signaling

and also below error I see in kamailio log
Sep 06 04:58:47 homer.ulsd.in kamailio[18066]: ERROR: sipcapture [sipcapture.c:2763]: pv_parse_hep_name(): REQUEST, PRE, 0x00b
Sep 06 04:58:47 homer.ulsd.in kamailio[18066]: ERROR: sipcapture [sipcapture.c:2763]: pv_parse_hep_name(): REQUEST, PRE, 0x00f
Sep 06 04:58:47 homer.ulsd.in kamailio[18066]: ERROR: sipcapture [sipcapture.c:2763]: pv_parse_hep_name(): REQUEST, PRE, 0x001
Sep 06 04:58:47 homer.ulsd.in kamailio[18066]: ERROR: sipcapture [sipcapture.c:2763]: pv_parse_hep_name(): REQUEST, PRE, 0x003
Sep 06 04:58:47 homer.ulsd.in kamailio[18066]: ERROR: sipcapture [sipcapture.c:2763]: pv_parse_hep_name(): REQUEST, PRE, 0x004
Sep 06 04:58:47 homer.ulsd.in kamailio[18066]: ERROR: sipcapture [sipcapture.c:2763]: pv_parse_hep_name(): REQUEST, PRE, 0x007
Sep 06 04:58:47 homer.ulsd.in kamailio[18066]: ERROR: sipcapture [sipcapture.c:2763]: pv_parse_hep_name(): REQUEST, PRE, 0x008
Sep 06 04:58:47 homer.ulsd.in kamailio[18066]: ERROR: sipcapture [sipcapture.c:2763]: pv_parse_hep_name(): REQUEST, PRE, 0x009
Sep 06 04:58:47 homer.ulsd.in kamailio[18066]: ERROR: sipcapture [sipcapture.c:2763]: pv_parse_hep_name(): REQUEST, PRE, 0x00a
Sep 06 04:58:47 homer.ulsd.in kamailio[18066]: ERROR: sipcapture [sipcapture.c:2763]: pv_parse_hep_name(): REQUEST, PRE, 0x011

Thanks...

**Comment by rhoribe** [comment]
Hi!
What's  solution ?

**Comment by prashantvidja** [comment]
Not sure, I solved long time ago but something issue in my mysql data.
