### ISSUE TITLE
Installer doesn't work without wget in Centos 7

### ISSUE THREAD

**Issue by lluisYasT** [sipcapture/homer-installer#37]
The installer fails silently in Centos 7 (minimal installation) if wget is not already installed.

**Comment by lmangani** [comment]
```
local base_pkg_list="wget autoconf automake bzip2 cpio curl curl-devel \
                       expat-devel fileutils make gcc gcc-c++ gettext-devel \
                       gnutls-devel openssl openssl-devel mod_ssl perl patch rsyslog \
                       unzip zip zlib zlib-devel bison flex pcre-devel libxml2-devel \
                       sox httpd php php-gd php-mysql php-json git php-mysql php-devel"
```

wget is actually the first package in the installation process. Do you have a log for this issue?

**Comment by Forty-Tw0** [comment]
I too had this problem, there was no output on the terminal other than the banner.
It looks like wget is used before it is actually installed.
https://github.com/sipcapture/homer-installer/blob/master/homer_installer.sh#L789
https://github.com/sipcapture/homer-installer/blob/master/homer_installer.sh#L798

**Comment by lmangani** [comment]
I doubt so, the `base_pkg_list` procedure installs the requirements before running them and I never noticed any issue with wget. The banner also points at a full installation log you can consult for errors - any chance you found one in the same directory you executed from?

**Comment by Forty-Tw0** [comment]
wget is used to download the kamailio repo before yum installs the base_pkg_list, line 789
`$cmd_wget --inet4-only --quiet --output-document=/etc/yum.repos.d/kamailio:v4.4.x-rpms.repo`

Then yum installs the base_pkg_list in addition to kamailio and mysql all at once, line 798
`$cmd_yum -y install $base_pkg_list $kamailio_pkg_list $mysql_pkg_list`

My /tmp/homer_installer.sh.pid.log only contains the top banner.
```
^[[3;J^[[H^[[2J**************************************************************

      ,;;;;;,       HOMER SIP CAPTURE (http://sipcapture.org)
     ;;;;;;;;;.     Single-Node Auto-Installer (beta 5.0.1)
   ;;;;;;;;;;;;;
  ;;;;  ;;;  ;;;;   <--------------- INVITE ---------------
  ;;;;  ;;;  ;;;;    --------------- 200 OK --------------->
  ;;;;  ...  ;;;;
  ;;;;       ;;;;   WARNING: This installer is intended for
  ;;;;  ;;;  ;;;;   dedicated/vanilla OS setups without any
  ,;;;  ;;;  ;;;;   customization and with default settings
   ;;;;;;;;;;;;;
    :;;;;;;;;;;     THIS SCRIPT IS PROVIDED AS-IS, USE AT
     ^;;;;;;;^      YOUR *OWN* RISK, REVIEW LICENSE & DOCS

**************************************************************
```

**Comment by lmangani** [comment]
You're right! the log path was removed from the banner, but still gets created at `/tmp/$(basename $0).$$.log` while the database details should be at `~root/homer_installer_user_details`

In terms of wget, we should check that - feel free to send a PR if you wish, but I'd also point out our installer instructions below:
```
cd /usr/src
wget https://cdn.rawgit.com/sipcapture/homer-installer/master/homer_installer.sh
chmod +x homer_installer.sh
./homer_installer.sh
```

So I guess an assumption was made there. @lluisYasT Did you curl it down?

Thanks!
