### ISSUE TITLE
Does not work after installation script

### ISSUE THREAD

**Issue by fagnersilva** [sipcapture/homer-installer#4]
After running the install script Homer 5 " bash <( curl -s https://cdn.rawgit.com/sipcapture/homer-installer/master/homer_installer.sh ) ," the kamailio lose records of extensions and this does not generate log to capture the web interface, I do not know what happens , can you help me?

**Comment by lmangani** [comment]
@fagnersilva HOMER is not meant to be running on the same Kamailio handling your calls and registrations. It requires a dedicated host acting as collector. Please check out our Wiki or the Installer Readme (installer expects a vanilla system and will demolish any existing setup)

The typical setup will have a Capture Server (sipcapture module kamailio) exclusively dedicated to the role and one or many Capture Agents (kamailio operational with siptrace module) used to mirror packets

If you haven't already I would suggest watching one of our presentations on the subject. Feel free to ask for help on our mailing-list if useful where our community is active helping out newcomers
