### ISSUE TITLE
Could not resolve all promises: could not load template

### ISSUE THREAD

**Issue by dancmsgit** [sipcapture/homer-installer#40]
Using the install script:
https://cdn.rawgit.com/sipcapture/homer-installer/master/homer_installer.sh

CentOS 7 (fresh install)

Receive 'Could not resolve all promises: could not load template' under: System Admin > Admin User

**Comment by maltris** [comment]
@lmangani May I ask why this was closed? I am having a similar problem and search for a possible solution.

**Comment by lmangani** [comment]
I can't tell since the content was edited.

**Comment by lmangani** [comment]
@aqsyonas could you take a look when you get a chance?

**Comment by maltris** [comment]
Update: My issue actually solved itself by setting LDAP_ADMIN_USERS in the preferences.php.

**Comment by lmangani** [comment]
That's great - closing this issue again :)
