### ISSUE TITLE
homer_installer.sh silent on error

### ISSUE THREAD

**Issue by udf2457** [sipcapture/homer-installer#42]
Am trying the `https://cdn.rawgit.com/sipcapture/homer-installer/master/homer_installer.sh` script (Single-Node Auto-Installer (beta 5.0.1)) on CentOS 7 (3.10.0-693.17.1.el7.x86_64 #1 SMP Thu Jan 25 20:13:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux release 7.4.1708 (Core) )

Running the script yields nothing but the pretty header and an exit code of "1". No messages, nothing in the logs ? Not particularly troubleshooting friendly !

**Comment by 00Asgaroth00** [comment]
Hi,

Logs should be in /tmp, but, if you want to see what it is doing try running the script as follows:

```
cd /usr/src
TRACE=1 ./homer_installer.sh
```

Send us all of the output of the trace to debug whats going wrong.
