### ISSUE TITLE
heplify 1.x tick installer

### ISSUE THREAD

**Issue by games130** [sipcapture/homer-installer#44]
I am manually installing the influxDB based on the script, for the line below should this be "sudo systemctl start chronograf" instread of "sudo systemctl start kapacitor"

https://github.com/sipcapture/homer-installer/blob/9f0328949278aa5055b09bcf7a487b076f3c6ffe/homer_installer.sh#L849

**Comment by lmangani** [comment]
@games130 thanks, feel free to apply those correction yourself and send a PR in the future, this is the beauty of opensource after all ;)

**Comment by negbie** [comment]
@games130 keep in mind that heplify-server was designed to work with prometheus. So you will get the best results with it. Influxdb support may come later.  When you need full influxdb support have a look at hepop.
