### ISSUE TITLE
The Installer doesn't Detect CentOS 7

### ISSUE THREAD

**Issue by sve71** [sipcapture/homer-installer#47]
Hello friends,

I have an issue with a new install of HOMER via the homer_installer.sh script. 
My colleagues have installed CentOS 7 on a VM, but its image was a little bit customized by them. When I started the script, it was displaying the error «Sorry, this Installer does not support your OS yet! ».
Is it possible to change the detect_linux_distribution() function to make the script detect the OS correctly?

The output of uname -a command:
_$ uname -a
Linux sipcapture01.unix.local 3.10.0-693.2.2.el7.x86_64 #1 SMP Sat Sep 9 03:55:24 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux_

Thanks a lot for any suggestions!

**Comment by lmangani** [comment]
@sve71 how was the installer modified?

**Comment by sve71** [comment]
Do you mean the installer of the OS (CentOS)?
It is not easy to say, because I do not know. System administrators built the image and I suppose they will not tell me what they exactly have changed.

However, I can print an output of bash commands. I hope it will help you to get the overview about the OS. Please, tell me, what would you like to see?

**Comment by sve71** [comment]
Hi again,
I've founf out that my collegues had deceived me. It's not CentOS, it's RHEL. Does the homer_installer work with this OS? The release info below:
[sve71@sipcapture01 ~]$ lsb_release
LSB Version:    :core-4.1-amd64:core-4.1-noarch

[sve71@sipcapture01 ~]$ hostnamectl
Static hostname: sipcapture01.unix.local
Icon name: computer-vm
Chassis: vm
Machine ID:
Boot ID:
Virtualization: vmware
Operating System: Red Hat Enterprise Linux
CPE OS Name: cpe:/o:redhat:enterprise_linux:7.4:GA:server
Kernel: Linux 3.10.0-693.2.2.el7.x86_64
Architecture: x86-64

[sve71@sipcapture01 ~]$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.4 (Maipo)

[sve71@sipcapture01 ~]$ cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.4 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.4"
PRETTY_NAME="Red Hat Enterprise Linux"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.4:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.4
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.4"

**Comment by lmangani** [comment]
Now it makes better sense - What you need to do to add support is extend the script [validation](https://github.com/sipcapture/homer-installer/blob/master/homer_installer.sh#L152) to cover your conditions but mind once you do, its not at all guaranteed all required packages will be available so you'll have to make sure EPEL or whatever equivalent in RHEL is providing the requirements.

FYI: We're presented and released the initial seed of Homer7 which does not have as many requirements as the previous one and makes things way more portable, so depending on the purpose and urgency you MIGHT want to try that instead of the older 5.x despite it being young perhaps.

**Comment by 00Asgaroth00** [comment]
@sve71 What is your output of:
```
# lsb_release -si
CentOS
# lsb_release -sr
7.4.1708
```
Might certainly be some differences in packages between RHEL and CentOS, even though CentOS is built from RHEL upstream. I dont have a copy of RHEL to test any changes with though.

@lmangani ooo homer-7 hey :100:  where can we find this initial release? I looked at homer project under homer-7 branch but it appears to be an empty repo.

**Comment by lmangani** [comment]
we're working on installers and containers as fast as possible - there are some major differences with the upgrade so its sort of tedious but should see the light soon on the repository. If you will have a chance to watch our recent and upcoming presentations, you will see all elements are actually there, only the instructions are missing.

**Comment by sve71** [comment]
Hi, @00Asgaroth00
The output is:

```
[sve71@sipcapture01 ~]$ lsb_release -si
RedHatEnterpriseServer
[sve71@sipcapture01 ~]$ lsb_release -sr
7.5
```

I followed the advice to extend the _homer_installer_ and it worked. Just in case, the part of the script is follow:
```
CentOS ) case "$distro_version" in
	   7* ) SETUP_ENTRYPOINT="setup_centos_7"
		return 0 ;; # Suported Distribution
	   *  ) return 1 ;; # Unsupported Distribution
	 esac
	 ;;
Red* ) case "$distro_version" in
	   7* ) SETUP_ENTRYPOINT="setup_centos_7"
		return 0 ;; # Suported Distribution
	   *  ) return 1 ;; # Unsupported Distribution
       esac
       ;;
```

@lmangani, it will be exciting to try H7 :-)
