### ISSUE TITLE
HOMER Install  kamailio homer_installer.sh Script fail 

### ISSUE THREAD

**Issue by pnlsantos** [sipcapture/homer-installer#48]
I am trying to install the kamailio script on a clean centOS 7 and get the error 

Total download size: 303 M
Installed size: 1.1 G
Downloading packages:
http://download.opensuse.org/repositories/home%3A/kamailio%3A/v5.0.x-rpms/CentOS_7/x86_64/kamailio-geoip-5.0.6-1.el7.centos.x86_64.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=home_kamailio_v5.0.x-rpms clean metadata
Trying other mirror.
http://download.opensuse.org/repositories/home%3A/kamailio%3A/v5.0.x-rpms/CentOS_7/x86_64/kamailio-ims-5.0.6-1.el7.centos.x86_64.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=home_kamailio_v5.0.x-rpms clean metadata
Trying other mirror.
http://download.opensuse.org/repositories/home%3A/kamailio%3A/v5.0.x-rpms/CentOS_7/x86_64/kamailio-jansson-5.0.6-1.el7.centos.x86_64.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=home_kamailio_v5.0.x-rpms clean metadata
Trying other mirror.
http://download.opensuse.org/repositories/home%3A/kamailio%3A/v5.0.x-rpms/CentOS_7/x86_64/kamailio-mysql-5.0.6-1.el7.centos.x86_64.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=home_kamailio_v5.0.x-rpms clean metadata
Trying other mirror.
http://download.opensuse.org/repositories/home%3A/kamailio%3A/v5.0.x-rpms/CentOS_7/x86_64/kamailio-5.0.6-1.el7.centos.x86_64.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=home_kamailio_v5.0.x-rpms clean metadata
Trying other mirror.
http://download.opensuse.org/repositories/home%3A/kamailio%3A/v5.0.x-rpms/CentOS_7/x86_64/kamailio-outbound-5.0.6-1.el7.centos.x86_64.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=home_kamailio_v5.0.x-rpms clean metadata
Trying other mirror.
http://download.opensuse.org/repositories/home%3A/kamailio%3A/v5.0.x-rpms/CentOS_7/x86_64/kamailio-sctp-5.0.6-1.el7.centos.x86_64.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=home_kamailio_v5.0.x-rpms clean metadata
Trying other mirror.
http://download.opensuse.org/repositories/home%3A/kamailio%3A/v5.0.x-rpms/CentOS_7/x86_64/kamailio-tls-5.0.6-1.el7.centos.x86_64.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=home_kamailio_v5.0.x-rpms clean metadata
Trying other mirror.
http://download.opensuse.org/repositories/home%3A/kamailio%3A/v5.0.x-rpms/CentOS_7/x86_64/kamailio-websocket-5.0.6-1.el7.centos.x86_64.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=home_kamailio_v5.0.x-rpms clean metadata
Trying other mirror.

Error downloading packages:
  kamailio-outbound-5.0.6-1.el7.centos.x86_64: [Errno 256] No more mirrors to try.
  kamailio-ims-5.0.6-1.el7.centos.x86_64: [Errno 256] No more mirrors to try.
  kamailio-websocket-5.0.6-1.el7.centos.x86_64: [Errno 256] No more mirrors to try.
  kamailio-mysql-5.0.6-1.el7.centos.x86_64: [Errno 256] No more mirrors to try.
  kamailio-sctp-5.0.6-1.el7.centos.x86_64: [Errno 256] No more mirrors to try.
  kamailio-5.0.6-1.el7.centos.x86_64: [Errno 256] No more mirrors to try.
  kamailio-jansson-5.0.6-1.el7.centos.x86_64: [Errno 256] No more mirrors to try.
  kamailio-tls-5.0.6-1.el7.centos.x86_64: [Errno 256] No more mirrors to try.
  kamailio-geoip-5.0.6-1.el7.centos.x86_64: [Errno 256] No more mirrors to try.

**Comment by gabyfulchic** [comment]
i've got the same issue exactly on a CentOS_7 vm.. i'm usgin virtualbox and i've also used the homer_installer git to get the same issue.. error downloading packages : No one mirrors to try for the kamailio packages...

Someone could help us ?

**Comment by lmangani** [comment]
Guys, we're moving forward to the new model using heplify-server as capture component. I suggest that route which was expressely created to avoid having to deal with 3rd party repositories and packages disappearing from day to night.

I'll take a stab at the installer later on today, if you use Docker, those are immediately available.

**Comment by 00Asgaroth00** [comment]
I just came across this issue too, but it turns out that I was behind a http proxy (squid), if I disable the proxy, then the download works. I'm not sure what the fix would be for this, possibly a setting in squid.

Were any of you using a proxy, or behind a transparent proxy of sorts when trying to run the script and encountered this issue?
