### ISSUE TITLE
adding homer5 metric support (elasticDB) without re-installing

### ISSUE THREAD

**Issue by JonConnor** [sipcapture/homer-installer#49]
is it possible to enable the homer5 bigdata support without re-installing and using the installer from the kamailio-5.x-metric repo?

**Comment by lmangani** [comment]
Hi @JonConnor it all depends what you installed to begin with. The best "bigdata" HOMER 5.x can produce are timeseries in InfluxDB or Prometheus. Check out the Docker containers here for examples: https://github.com/sipcapture/homer-docker/tree/master/heplify-server

Elasticsearch is not part of the picture right now but can easily be made so.

**Comment by JonConnor** [comment]
@lmangani Hi, i was referring to the information provided from this git: https://github.com/sipcapture/homer/wiki/Homer-Bigdata.  

In it it states some basic metrics are supported (i'm just looking to aggregate Registers In, Invites In, error Responses).  It listed InfluxDB, ElasticSearch, and graylog as supported.  

The instructions were to use the homer_installer.sh from the metric branch to install homer.  However, when i installed homer i just used the installer from the main branch.

**Comment by JonConnor** [comment]
@Imangani also to be clear, I already have an ELK stack running separately.

**Comment by lmangani** [comment]
@JonConnor that's pretty old and will soon be removed. Mind you CAN actually do what it says, but you'll have to get your hands dirty. I would suggest looking into a switch to heplify-server as it already allows you to aggregate by methods, statistics and so on via its prometheus output which can easily be converted to anything else via Telegraf and other tools. Hope this helps!

**Comment by JonConnor** [comment]
@lmangani ok cool thanks for the tip!  I'll look more into heplify-server.
