### ISSUE TITLE
issue after system reboot or mysqld service restart

### ISSUE THREAD

**Issue by emdici** [sipcapture/homer-installer#5]
Hi guy's

I'm trying to install Homer on centos 7 with the bash script...
after a couple of installs i find out the right way to make it work...

yum -y install nano
nano /etc/selinux/config selinix=disabled

systemctl disable firewalld
systemctl stop firewalld
systemctl status firewalld

yum install -y perl-DBD-MySQL

bash <( curl -s https://cdn.rawgit.com/sipcapture/homer-installer/master/homer_installer.sh )

anyway if i reboot the system or restart mysqld service 
1. there is no way to login the UI as the user/password is not recognized..
2. homer rotate script doesen't work anymore

if i rerun the script again i am able to login the UI again but the rotate script don't want to work..

any suggestions?

Best Regards

Marco

**Comment by emdici** [comment]
Hi Lorenzo,

first of all thank you for the fast answer, i'm sorry for my wrong posting... it's my first time :)

At first sight it seems your DB is not persistent. Is this a normal host or some virtualization/container?

-my system is on centos7 virtual machine on an esxi server in a datacenter

**Comment by voipmarco** [comment]
Hi,
Ok, now i changed my storage on vm to persistent and installed a fresh centos 7 and Homer but i regcognize the exact same problems...  

/Marco

**Comment by lmangani** [comment]
Hi Marco,

The database is as persistent as your volumes on a normal install - check your VM settings/preferences and feel free to reopen if you have logs or other information.

**Comment by emdici** [comment]
Hi Lorenzo,

fresh install centos7 wit install script:

basically i tried to install the script on:
1. VM with HDD setted to persistent storage
2. On a centos7 installed directly(NO VM) on a raid10 dell poweredge 2950 
3. On a Workstation 12 on my PC

issue: after restarting service mysqld i'm not able to login to the UI (email and password combination not recognized)
- all services are running without showing any errors
- /opt/homer_rotate  not showing any errors
- http://192.168.69.223/api/v1/test    Your api call works! Well done!
- http://192.168.69.223/api/v1/session:

{
    "sid": "3g79gm13guhelr9sdqh3bgivo3",
    "auth": "false",
    "status": 403,
    "message": "wrong session",
    "data": [

```
]
```

}

i tried to do everything i was able to find about this but with no luck...  

logs in attachment:

[logs.zip](https://github.com/sipcapture/homer-installer/files/428688/logs.zip)

**Comment by lmangani** [comment]
I think the following error is the culprit:

```
Your password does not satisfy the current policy requirements
```

login with mysql -u root -p and check the current policy rules by:

```
# SHOW VARIABLES LIKE 'validate_password%';
+--------------------------------------+--------+
| Variable_name                        | Value  |
+--------------------------------------+--------+
| validate_password_dictionary_file    |        |
| validate_password_length             | 5      |
| validate_password_mixed_case_count   | 1      |
| validate_password_number_count       | 1      |
| validate_password_policy             | MEDIUM |
| validate_password_special_char_count | 1      |
+--------------------------------------+--------+
```

Then you can change any of the above variables at your will:

```
# SET GLOBAL validate_password_length = 5;
# SET GLOBAL validate_password_number_count = 0;
# SET GLOBAL validate_password_mixed_case_count = 0;
# SET GLOBAL validate_password_special_char_count = 0;
```

**Comment by emdici** [comment]
Hi Lorenzo!

i feel soo stupid.. ;)

i installed all from scratch again, after install i login with default
credentials and changed the admin password to a password with that matches
the policy needings and now everything works !!!

very appreciate your help

Thanks Marco
