### ISSUE TITLE
auth error login homer interface

### ISSUE THREAD

**Issue by gabyfulchic** [sipcapture/homer-installer#50]
FULCHIC Gaby
Aujourd’hui, 11:12
![autherror](https://user-images.githubusercontent.com/22600727/41964644-d62b2b2e-79fa-11e8-9f2a-867fc5dac5de.png)

I've juste installed homer5 with that script : https://github.com/sipcapture/homer-installer
I'm on windows 10 using virtualbox and a Debian 8 jessie vm.

But now when i'm trying to access to the homer interface, it asks me some credentials. So i've checked in my database homer_configuration the users to login. But the passwords obviously and it's legit are encrypted. So can you help me to get the " Admin"  password or the " noc"  password ? 

Ps : I've tried using Admin/test123 and Admin/Admin and same with my DB_username and password.

**Comment by lmangani** [comment]
mind things are case sensitive and `Admin` != `admin` could you confirm this is not the issue?
Also, please confirm mysql is actually up and running, providing the authentication backend.

**Comment by gabyfulchic** [comment]
I've tried using admin/test123 admin/test1234 and admin/admin but nothing, again tha error.

mysql Status : 
![mysqlstatus](https://user-images.githubusercontent.com/22600727/41965399-bb23bbdc-79fc-11e8-8350-e577ccb9210a.png)

**Comment by lmangani** [comment]
Can you access mysql using the credentials configured in homer - that's likely the issue.

**Comment by gabyfulchic** [comment]
I'm using this config on homer web folder.
![dbconf](https://user-images.githubusercontent.com/22600727/41966753-4450f7b4-7a00-11e8-9f89-7e375b86ee99.png)

And i've got this issue when i log in msql with homer user.
![errrologdbhomer](https://user-images.githubusercontent.com/22600727/41966798-5f818c7e-7a00-11e8-8bef-156a5c3db820.png)

**Comment by lmangani** [comment]
You just found the issue. Please provide the config with a valid username/password and login should work. Make sure the same is done on the capture server front for inserts.

The installer should have created a log in its root directory - please check it for errors, too.

**Comment by gabyfulchic** [comment]
ok ty, but by valid username/password you mean Homer33/Passw0rd33 for example ?
On the capture server front for inserts ? hm i don't really understand that part.

Ok i'll check the logs too.

Ty so much

**Comment by lmangani** [comment]
@gabyfulchic sorry if i confused you. Login to your mysql as root and create a valid user w/ permissions to write. Once done, use those credentials in the HOMER configuration and try again.

**Comment by gabyfulchic** [comment]
Oh no it's ok @lmangani  i'm just a newbie in the system world, i just begin. Do you want to say insert in the homer user table a user ? Or CREATE USER in sql cmd ?
Oh no my bad i understood. I'll create a sql user and just use it in db_username and db_password ! ty really much.

**Comment by gabyfulchic** [comment]
hum, same modifiying the configuration after created a new user with grant all privileges it doesn't work..
(i tested, i can acces to sql cmd with mysql -u homergaby -p Password)

![image](https://user-images.githubusercontent.com/22600727/41971725-b4e6def8-7a0f-11e8-9481-800e26060222.png)

![image](https://user-images.githubusercontent.com/22600727/41971786-eb188bf2-7a0f-11e8-95c6-1c9253a2468b.png)

**Comment by lmangani** [comment]
@gabyfulchic the login remains admin/test123 - this is stored INSIDE MySQL and has nothing to do with the user HOMER will access MySQL with. So, the settings in php should be fine, but you need to use the actual credentials next.

**Comment by gabyfulchic** [comment]
So i created a new user to connect to the mysql databases, and then i need to use the credentials admin/test123 ? because i've tested too and it doesn't work.. :(

**Comment by gabyfulchic** [comment]
Oh my godness, it's ok it's my fault. i was typing the wrong password, the default credentials are here 👍 
https://github.com/QXIP/homer-docker/issues/3

It was admin/test1234
