### ISSUE TITLE
decoding issue. 

### ISSUE THREAD

**Issue by johandeclercqdemocon** [sipcapture/homer-installer#51]
I installed homer 5 using this link as described in issue #34 : 
git clone https://github.com/sipcapture/homer-installer.git -b stretch-kamailio-5.x

The opensips involved sends the packets correctly (using hep 3 format). 

When I look in syslog : 

Sep 24 22:16:50 ns365555 homer[15930]: ERROR: sipcapture [sipcapture.c:2711]: nosip_hep_msg(): couldn't parse sip message
Sep 24 22:16:50 ns365555 homer[15930]: ERROR: <core> [core/parser/msg_parser.c:330]: parse_headers(): bad header field [(null)]
Sep 24 22:16:50 ns365555 homer[15932]: ERROR: sipcapture [sipcapture.c:2711]: nosip_hep_msg(): couldn't parse sip message
Sep 24 22:16:50 ns365555 homer[15932]: ERROR: <core> [core/parser/msg_parser.c:330]: parse_headers(): bad header field [(null)]
Sep 24 22:16:50 ns365555 homer[15932]: ERROR: sipcapture [sipcapture.c:2711]: nosip_hep_msg(): couldn't parse sip message
Sep 24 22:16:50 ns365555 homer[15932]: ERROR: <core> [core/parser/msg_parser.c:330]: parse_headers(): bad header field [(null)]
Sep 24 22:16:50 ns365555 homer[15929]: ERROR: sipcapture [sipcapture.c:2711]: nosip_hep_msg(): couldn't parse sip message
Sep 24 22:16:50 ns365555 homer[15929]: ERROR: <core> [core/parser/msg_parser.c:330]: parse_headers(): bad header field [(null)]
Sep 24 22:16:50 ns365555 homer[15933]: ERROR: sipcapture [sipcapture.c:2711]: nosip_hep_msg(): couldn't parse sip message
Sep 24 22:16:50 ns365555 homer[15933]: ERROR: <core> [core/parser/msg_parser.c:330]: parse_headers(): bad header field [(null)]
Sep 24 22:16:50 ns365555 homer[15930]: ERROR: sipcapture [sipcapture.c:2711]: nosip_hep_msg(): couldn't parse sip message
Sep 24 22:16:50 ns365555 homer[15930]: ERROR: <core> [core/parser/msg_parser.c:330]: parse_headers(): bad header field [(null)]
Sep 24 22:16:52 ns365555 homer[15931]: ERROR: sipcapture [sipcapture.c:2711]: nosip_hep_msg(): couldn't parse sip message
Sep 24 22:16:52 ns365555 homer[15932]: ERROR: sipcapture [sipcapture.c:2711]: nosip_hep_msg(): couldn't parse sip message
Sep 24 22:16:52 ns365555 homer[15931]: ERROR: <core> [core/parser/msg_parser.c:330]: parse_headers(): bad header field [(null)]
Sep 24 22:16:52 ns365555 homer[15932]: ERROR: <core> [core/parser/msg_parser.c:330]: parse_headers(): bad header field [(null)]
Sep 24 22:16:52 ns365555 homer[15929]: ERROR: sipcapture [sipcapture.c:2711]: nosip_hep_msg(): couldn't parse sip message
Sep 24 22:16:52 ns365555 homer[15929]: ERROR: <core> [core/parser/msg_parser.c:330]: parse_headers(): bad header field [(null)]
Sep 24 22:16:52 ns365555 homer[15933]: ERROR: sipcapture [sipcapture.c:2711]: nosip_hep_msg(): couldn't parse sip message
Sep 24 22:16:52 ns365555 homer[15933]: ERROR: <core> [core/parser/msg_parser.c:330]: parse_headers(): bad header field [(null)]

Can you please indicate what I am overlooking ?

Thanks and best regards, 
Johan. 

[mydump.zip](https://github.com/sipcapture/homer-installer/files/2412737/mydump.zip)

**Comment by lmangani** [comment]
Hi @johandeclercqdemocon this would suggest non-HEP packets are entering the circuit ... could be keep alives or anything really. Are valid messages captured and displayed correctly?

**Comment by johandeclercqdemocon** [comment]
Hi Lorenzo,

I have attached a pcap. It’s opensips 24 on the other end and the sent messages seem valid.

Outlook voor iOS<https://aka.ms/o0ukef> downloaden

________________________________
Van: Lorenzo Mangani <notifications@github.com>
Verzonden: maandag, september 24, 2018 11:47 PM
Aan: sipcapture/homer-installer
CC: johandeclercqdemocon; Mention
Onderwerp: Re: [sipcapture/homer-installer] decoding issue. (#51)


Hi @johandeclercqdemocon<https://github.com/johandeclercqdemocon> this would suggest non-HEP packets are entering the circuit ... could be keep alives or anything really. Are valid messages captured and displayed correctly?

**Comment by johandeclercqdemocon** [comment]
Hi Lorenzo, 
I have changed my opensips config for default values. 
The packets do arrive at the correct server, but they cannot be inserted. 
To me the packet seems valid as they are properly decoded in wireshark. 
[forhomer.zip](https://github.com/sipcapture/homer-installer/files/2437005/forhomer.zip)



Oct  2 08:00:05 ns3019374 homer[22749]: ERROR: db_mysql [km_dbase.c:127]: db_mysql_submit_query(): driver error on query: Incorrect string value: '\xE0.\x$
Oct  2 08:00:05 ns3019374 homer[22749]: ERROR: <core> [db_query.c:235]: db_do_insert_cmd(): error while submitting query
Oct  2 08:00:05 ns3019374 homer[22749]: ERROR: db_mysql [km_dbase.c:127]: db_mysql_submit_query(): driver error on query: Incorrect string value: '\xE0.\x$
Oct  2 08:00:05 ns3019374 homer[22749]: ERROR: <core> [db_query.c:235]: db_do_insert_cmd(): error while submitting query
Oct  2 08:00:05 ns3019374 homer[22749]: ERROR: db_mysql [km_dbase.c:127]: db_mysql_submit_query(): driver error on query: Incorrect string value: '\xE0.\x$
Oct  2 08:00:05 ns3019374 homer[22749]: ERROR: <core> [db_query.c:235]: db_do_insert_cmd(): error while submitting query
Oct  2 08:00:05 ns3019374 homer[22749]: ERROR: db_mysql [km_dbase.c:127]: db_mysql_submit_query(): driver error on query: Incorrect string value: '\xE0.\x$
Oct  2 08:00:05 ns3019374 homer[22749]: ERROR: <core> [db_query.c:235]: db_do_insert_cmd(): error while submitting query
Oct  2 08:00:05 ns3019374 homer[22749]: ERROR: sipcapture [sipcapture.c:1593]: sip_capture_store(): failed to insert into database(second attempt)
Oct  2 08:00:07 ns3019374 homer[22752]: ERROR: db_mysql [km_dbase.c:127]: db_mysql_submit_query(): driver error on query: Incorrect string value: '\xC8\x1$
Oct  2 08:00:07 ns3019374 homer[22752]: ERROR: <core> [db_query.c:235]: db_do_insert_cmd(): error while submitting query
Oct  2 08:00:07 ns3019374 homer[22752]: ERROR: db_mysql [km_dbase.c:127]: db_mysql_submit_query(): driver error on query: Incorrect string value: '\xC8\x1$
Oct  2 08:00:07 ns3019374 homer[22752]: ERROR: <core> [db_query.c:235]: db_do_insert_cmd(): error while submitting query
Oct  2 08:00:07 ns3019374 homer[22752]: ERROR: db_mysql [km_dbase.c:127]: db_mysql_submit_query(): driver error on query: Incorrect string value: '\xC8\x1$
Oct  2 08:00:07 ns3019374 homer[22752]: ERROR: <core> [db_query.c:235]: db_do_insert_cmd(): error while submitting query
