### ISSUE TITLE
Heplify service not starting

### ISSUE THREAD

**Issue by aparajey** [sipcapture/homer-installer#56]
i have installed homer 7 on debian 9, everything working fine but heplify service not starting.

![Screenshot 2019-05-26 at 3 11 09 PM](https://user-images.githubusercontent.com/23430485/58379979-83a00580-7fc8-11e9-9ac4-08eeab9b6d47.png)

Any suggestion on this?

**Comment by aqsyonas** [comment]
@aparajey the correct name for the service is  `heplify-server` . 
Please, let me know if you are still unable to start it. 

`systemctl status heplify-server`

**Comment by aparajey** [comment]
@aqsyonas yes i can start it now, thanks. But even though my servers are properly configured to send SIP packets to Homer it isn't showing up on homer dashboard. firewall is also disabled so i am sure it is not blocking it. any idea what could be the issue?

**Comment by aqsyonas** [comment]
ok, great. Then I will close this ticket. The proper way for other issues would be using homer google group.

**Comment by steveolu** [comment]
heplify.service                      loaded activating auto-restart Captures interestng packets from wire and sends them to Heplify-Server

after installation, heplify is not active. How can I fix this?

**Comment by lmangani** [comment]
@steveolu check the logs and resolve the errors preventing it from starting. This is a thread from 2019
