### ISSUE TITLE
Access HOMER UI

### ISSUE THREAD

**Issue by pnlsantos** [sipcapture/homer-installer#57]
Hi have installed homer 7 with the script https://github.com/sipcapture/homer-installer in a fresh centos7 but I cannot access web GUI.
does it need to start any node script? it should not be a web server installed?

[homer_installer.sh.436.log](https://github.com/sipcapture/homer-installer/files/3266478/homer_installer.sh.436.log)

**Comment by pnlsantos** [comment]
> homer-app@1.0.7 start /opt/homer-app
> node bootstrap.js

/opt/homer-app/server/server.js:82
    throw error;
    ^

Error: Could not find openssl on your system on this path: openssl
    at /opt/homer-app/node_modules/pem/lib/openssl.js:237:23
    at F (/opt/homer-app/node_modules/pem/node_modules/which/which.js:68:16)
    at E (/opt/homer-app/node_modules/pem/node_modules/which/which.js:80:29)
    at /opt/homer-app/node_modules/pem/node_modules/which/which.js:89:16
    at /opt/homer-app/node_modules/isexe/index.js:42:5
    at /opt/homer-app/node_modules/isexe/mode.js:8:5
    at FSReqWrap.oncomplete (fs.js:153:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! homer-app@1.0.7 start: `node bootstrap.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the homer-app@1.0.7 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-07T15_10_20_518Z-debug.log

**Comment by aqsyonas** [comment]
@pnlsantos could you please pull the latest script and give it a shot. It should be fixed now.

**Comment by aqsyonas** [comment]
closing due to no response.
