### ISSUE TITLE
listening port

### ISSUE THREAD

**Issue by yumminova** [sipcapture/homer-installer#59]
Hi, i installed version 5 as i could not get 7 to work, but it seems its listening on tcp6 instead of tcp, how can i change that?

**Comment by yumminova** [comment]
oh actually it seems im running 7 ))))

**Comment by lmangani** [comment]
We can support you with 7 - what's your determination based on and could you kindly list the status of the various services?

**Comment by lmangani** [comment]
Note
```
The tcp6 LISTEN entry is an AF_INET6 socket, so it will accept both IPv4 and IPv6 incoming connections.
```

so most likely it works just fine. Could you confirm?

**Comment by yumminova** [comment]
hi and sorry for the late response!

Yes its actually working.

So is there any documentation on the dashboard? I remember in version 5 , or maybe older, i had a great default dashboard with a lot of info, but now i have only a search field.

I mean it would work, but there must be more possible?

**Comment by aqsyonas** [comment]
@yumminova homer7 is better feature-rich and flexible than homer5. You can easily integrate other systems with it.  Like, can send stats to influxdb and configure a couple of alarm based upon your requirements. You can find at below link some default dashboards. 

https://github.com/sipcapture/homer7-docker/tree/master/heplify-server/hom7-hep-prom-graf/grafana/provisioning

If you provide us with more details about the features you would like to see in homer7 maybe we can help you in a better way
