### ISSUE TITLE
Bash Installer Missing /opt/rotation.ini

### ISSUE THREAD

**Issue by bjordan9** [sipcapture/homer-installer#6]
Just a little background, this was a reinstall from an older version. When installing utilizing the bash script on debian 8 I had the error that the file /opt/rotation.ini was missing. After copying the files from the git repo in /usr/src/homer-api/scripts/ and rerunning the install script everything seemed fine. 

I think the culprit is around the if block near line 380 in the homer_installer.sh script. If you are cloning the repo it copies the scripts to /opt/ but if you already have the repos from an older version it never copies the contents of the /usr/src/homer-api/scripts/ directory.

**Comment by bjordan9** [comment]
I am new to the github experience, but I added a pull request #7 that I think fixes the issue. It also includes a fix for kamailio to use a sources.list.d entry instead of appending into the sources.list file every time the script runs.

**Comment by lmangani** [comment]
can you confirm if this can be closed post-merge? thanks in advance!

**Comment by bjordan9** [comment]
It worked for me so I will close out the issue.
