### ISSUE TITLE
cannot access gui after installing  HOMER 7

### ISSUE THREAD

**Issue by shchbo** [sipcapture/homer-installer#60]
after installing HOMER 7 on centos 7 i cannot access the UI.
on some computers i get a white screen and on some i get the login screen after a wile but when i type the username and password i get a message that its incorrect.
at home it woks OK so i am guessing it has something to do with the network at work but i do not know what.
when i ran this command at home : curl -X POST localhost:80/api/v3/auth -d "username=admin&password=sipcapture
i get a token
when i run it at work i get an authentication error.

**Comment by aqsyonas** [comment]
@shchbo, please capture the traffic on port 80 using below command when you try to login remotely. 
And see if you spot anything amiss. 
`ngrep -W byline -q -d any port 80`

**Comment by lmangani** [comment]
The UI might try to fetch a few libraries - I would guess one of the locations firewalls a few. Check from the browser console if you see any errors or timeouts while fetching data.

**Comment by aqsyonas** [comment]
@shchbo please fetch lastest code of homer-installer. There were some fixes related to SELinux.
