### ISSUE TITLE
installer fails

### ISSUE THREAD

**Issue by jerry6021** [sipcapture/homer-installer#61]
Brand new Debian 9 installation

Did the following
-------------------------
cd /usr/src
wget https://cdn.rawgit.com/sipcapture/homer-installer/master/homer_installer.sh
chmod +x homer_installer.sh
./homer_installer.sh
-------------------------

Got these errors (installed as root):

Clone done
Installing Homer-App

> utf-8-validate@4.0.0 install /opt/homer-app/node_modules/utf-8-validate
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.3.0
prebuild-install info looking for local prebuild @ prebuilds/utf-8-validate-v4.0.0-node-v64-linux-x64.tar.gz
prebuild-install WARN install EACCES: permission denied, access '/root/.npm'
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/10.16.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/opt/homer-app/node_modules/utf-8-validate/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/opt/homer-app/node_modules/utf-8-validate/.node-gyp'
gyp ERR! System Linux 4.9.0-7-amd64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/homer-app/node_modules/utf-8-validate
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN @babel/plugin-transform-async-to-generator@7.0.0-beta.40 requires a peer of @babel/core@7.0.0-beta.40 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.3.1 requires a peer of popper.js@^1.14.7 but none is installed. You must install peer dependencies yourself.
npm WARN less-loader@2.2.3 requires a peer of less@^2.3.1 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-dev-middleware@3.4.0 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-dev-server@3.1.14 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN homer-app@1.0.7 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.8 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! utf-8-validate@4.0.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the utf-8-validate@4.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-25T04_33_53_644Z-debug.log

==============================================
Bottom of log file has 
==============================================

1213 silly saveTree     │   │ ├── graceful-fs@4.1.15
1213 silly saveTree     │   │ └── strip-bom@3.0.0
1213 silly saveTree     │   └── path-type@2.0.0
1213 silly saveTree     ├─┬ string-width@2.1.1
1213 silly saveTree     │ ├── is-fullwidth-code-point@2.0.0
1213 silly saveTree     │ └─┬ strip-ansi@4.0.0
1213 silly saveTree     │   └── ansi-regex@3.0.0
1213 silly saveTree     ├── which-module@2.0.0
1213 silly saveTree     └── yargs-parser@7.0.0
1214 warn @babel/plugin-transform-async-to-generator@7.0.0-beta.40 requires a peer of @babel/core@7.0.0-beta.40 but none is installed. You must install peer dependencies yourself.
1215 warn bootstrap@4.3.1 requires a peer of popper.js@^1.14.7 but none is installed. You must install peer dependencies yourself.
1216 warn less-loader@2.2.3 requires a peer of less@^2.3.1 but none is installed. You must install peer dependencies yourself.
1217 warn webpack-dev-middleware@3.4.0 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
1218 warn webpack-dev-server@3.1.14 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
1219 warn homer-app@1.0.7 No repository field.
1220 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.8 (node_modules/fsevents):
1221 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
1222 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
1222 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
1222 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
1222 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
1223 verbose stack Error: utf-8-validate@4.0.0 install: `prebuild-install || node-gyp rebuild`
1223 verbose stack Exit status 1
1223 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
1223 verbose stack     at EventEmitter.emit (events.js:198:13)
1223 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
1223 verbose stack     at ChildProcess.emit (events.js:198:13)
1223 verbose stack     at maybeClose (internal/child_process.js:982:16)
1223 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
1224 verbose pkgid utf-8-validate@4.0.0
1225 verbose cwd /opt/homer-app
1226 verbose Linux 4.9.0-7-amd64
1227 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
1228 verbose node v10.16.0
1229 verbose npm  v6.9.0
1230 error code ELIFECYCLE
1231 error errno 1
1232 error utf-8-validate@4.0.0 install: `prebuild-install || node-gyp rebuild`
1232 error Exit status 1
1233 error Failed at the utf-8-validate@4.0.0 install script.
1233 error This is probably not a problem with npm. There is likely additional logging output above.
1234 verbose exit [ 1, true ]
~

**Comment by aqsyonas** [comment]
@jerry6021 thanks for the report looks like need to enable --unsafe-perm during the installation of packages. I will fix that.

**Comment by aqsyonas** [comment]
@jerry6021 could you please pull the latest changes and try. Or you can check below commit. 

https://github.com/sipcapture/homer-installer/commit/34a4ecaeefd57b83edd478eb0f487b32b69c1b68
