### ISSUE TITLE
installer fails with npm ImportError: No module named compiler.ast

### ISSUE THREAD

**Issue by ericiper** [sipcapture/homer-installer#63]
Hello
I'm using the homer7_installer.sh script on a fresh debian 9.9 - Installer failed with error : installer fails with npm ImportError: No module named compiler.ast

I've solved this installing python-dev: apt install python-dev (and to be safe, apt install python3-dev). Install looks ok by just relaunching the install script.

E.

**Comment by aqsyonas** [comment]
@ericiper thanks we will add this as a dependency.

**Comment by aqsyonas** [comment]
fixed here cafa61f

Thanks.
