### ISSUE TITLE
Post-Install message gives the wrong service name to start and stop

### ISSUE THREAD

**Issue by SB-JohnK** [sipcapture/homer-installer#65]
The message that is displayed after running homer_installer.sh is: 

    * Start/stop Homer SIP Capture:
         'systemctl start|stop heplify'

The command is actually systemctl start|stop heplify-server

**Comment by lmangani** [comment]
Patched! Thanks for the suggestion :) 

https://github.com/sipcapture/homer-installer/blob/master/homer_installer.sh
