### ISSUE TITLE
Capturing VoIP Phones

### ISSUE THREAD

**Issue by Justessej** [sipcapture/homer-installer#72]
I finished the installer and its working fine. But its all emty and i want to start monitoring my VoIP Phones. Hope someone will help me :)

**Comment by aqsyonas** [comment]
homer just displays what hep agents send to it. So, most probably you need to install heplify/capagent on your voip servers where your phones get registered.

**Comment by Justessej** [comment]
So i need to install the capture tool on the VoIP server not on the server homer is running

**Comment by lmangani** [comment]
@Justessej the capture server receives packets generated by an `HEP` agent, such as `heplify`, `captagent` or any native HEP client integrated in platforms like `kamailio`, `opensips`, `freeswitch`, `asterisk` and others.

**Comment by Justessej** [comment]
So you dont need to install captagent you must find a supported agent for homer to capture

**Comment by Justessej** [comment]
Do you need a captagent to let homer work. Isnt possible that it can scan the intern network

**Comment by lmangani** [comment]
@Justessej this is a pretty broad of a scope for this issue - perhaps you do, but its important to understand what you're about to do before making decisions - perhaps watch one (any) of my presentations about the HOMER architecture and it should answer your questions

**Comment by Justessej** [comment]
But is there a program that can be used as SIP sniffer that can scan the intern network at the company

**Comment by lmangani** [comment]
That's called a `Capture Agent` and we have many. Start with `heplify` for simplicity.
