### ISSUE TITLE
ERROR: You need the following minimal set of commands installed

### ISSUE THREAD

**Issue by vlad-dc** [sipcapture/homer-installer#81]
Hello,

I tried to install homer with bash script Auto-Installer (beta 7.7) on Debian 10 and 9, but getting next error:
______
ERROR: You need the following minimal set of commands installed:

       lsb-release wget curl git
______
The system have all commands:
lsb_release -si
Debian
lsb_release -sr
10

Best regards.

**Comment by andycol** [comment]
Thanks for poining that out! i have just patched it and merged the change to master.
Please do a git pull and it will now work

fixed [lsb fix](https://github.com/sipcapture/homer-installer/commit/14bf2f06e0db3a194c80f5897d3e713ffeafdeab)

**Comment by vlad-dc** [comment]
Andrew, 

Works fine right now. Thanks!

Regards!
