### ISSUE TITLE
cannot send data from sngrep to homer

### ISSUE THREAD

**Issue by ghost** [sipcapture/homer-installer#83]
Hello, 

I installed homer with the script and everything is good. i can acces to the interface and everything seems ok on that side. My issue is when i want to send data from sngrep to homer, it seems like it does not go at all.

**sngrep  port 5060 -H udp:xxx:9060 --no-interface
Dialog count: 8**

on sngrep i have 8 event but no data in my homer

**Comment by lmangani** [comment]
Can you see other traffic? Or this is a general issue? Are firewall ports open? Did you select a time range? etc etc

It's usually a good idea to run the [hepgen test](https://github.com/sipcapture/homer/wiki/HEPGEN-Test) on a new install to make sure you can see traffic in general before troubleshooting other HEP clients. You can run hepgen from both local and a remote system to be sure everything flows. Hope this helps!

**Comment by ghost** [comment]
Thank you for your answer

i stopped the firewall on the homer server, and when i run the hepjen test homer receive the datas, seems like it is on my side. can i have a hint please ?

the range in the homer interface is the last 15 minutes 

i run the test on both servers and both works

**Comment by lmangani** [comment]
If hepgen works, I would suggest using one of our agents, such as `heplify` to capture and send traffic from remote hosts
