### ISSUE TITLE
Install failed on debian 10/11

### ISSUE THREAD

**Issue by chabeaumont** [sipcapture/homer-installer#84]
Hello everyone,

I'm very newbie to the project, i'm trying to install homer on debian 10 or 11. Both have the same issue during the install with the install script link to the gpg key on package cloud.

 
_Installing Homer-App
Detected operating system as debian/buster.
Checking for curl...
Detected curl...
Checking for gpg...
Detected gpg...
Running apt-get update... done.
Installing debian-archive-keyring which is needed for installing
apt-transport-https on many Debian systems.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/qxip_sipcapture.list...done.
Importing packagecloud gpg key... curl: (28) Operation timed out after 300175 milliseconds with 0 out of 0 bytes received
gpg: aucune donnée OpenPGP valable n'a été trouvée.
done.
Running apt-get update... done._

The curl command seems to not working and finish by timeout 
_curl -L https://packagecloud.io/qxip/sipcapture/gpgkey | sudo apt-key add -_

 I've tried to install the key manually by download it on local :
_cat qxip-sipcapture-6B83EE56C4F39C80.pub | sudo apt-key add -_

And now i'm facing this issue :

_apt-get update
Atteint :1 http://apt.postgresql.org/pub/repos/apt buster-pgdg InRelease
Atteint :2 http://security.debian.org/debian-security buster/updates InRelease
Atteint :3 http://deb.debian.org/debian buster InRelease
Atteint :4 http://deb.debian.org/debian buster-updates InRelease
Ign :5 https://packagecloud.io/qxip/sipcapture/debian buster InRelease
Err :6 https://packagecloud.io/qxip/sipcapture/debian buster Release
  Could not wait for server fd - select (11: Ressource temporairement non disponible) [IP : 52.222.196.119 443]
Lecture des listes de paquets... Fait
E: Le dépôt https://packagecloud.io/qxip/sipcapture/debian buster Release n'a pas de fichier Release.
N: Les mises à jour depuis un tel dépôt ne peuvent s'effectuer de manière sécurisée, et sont donc désactivées par défaut.
N: Voir les pages de manuel d'apt-secure(8) pour la création des dépôts et les détails de configuration d'un utilisateur._

**Comment by andycol** [comment]
Hi 

Can you confirm your server has connection to 52.222.196.119 on port 443?
you can test with either telnet 52.222.196.119 443
or nc -zv 52.222.196.119  443
if it works you should see
Connection to 52.222.196.119 443 port [tcp/https] succeeded!

**Comment by lmangani** [comment]
The full repository setup process is also available here: https://packagecloud.io/qxip/sipcapture/install

**Comment by chabeaumont** [comment]
Thank you for your quick answers, seems to work : 

root@DIGPRHOMER01:/homer-installer# telnet 52.222.196.119 443
Trying 52.222.196.119...
Connected to 52.222.196.119.
Escape character is '^]'.
¨
Connection closed by foreign host.
root@DIGPRHOMER01:~/homer-installer# nc -zv 52.222.196.119 443
server-52-222-196-119.cdg50.r.cloudfront.net [52.222.196.119] 443 (https) open

**Comment by chabeaumont** [comment]
> The full repository setup process is also available here: https://packagecloud.io/qxip/sipcapture/install

Yes, i've tried a wget but failed :

_root@DIGPRHOMER01:~/homer-installer# wget --content-disposition https://packagecloud.io/qxip/sipcapture/packages/debian/buster/homer-app_1.4.30_amd64.deb/download.deb
--2022-02-01 12:17:22--  https://packagecloud.io/qxip/sipcapture/packages/debian/buster/homer-app_1.4.30_amd64.deb/download.deb
Resolving packagecloud.io (packagecloud.io)... 13.57.99.230, 52.52.107.175, 2600:1f1c:2e5:6900:5d6d:7342:dbda:a3ce, ...
Connecting to packagecloud.io (packagecloud.io)|13.57.99.230|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://d28dx6y1hfq314.cloudfront.net/1632/11441/debian/package_files/3261921.deb?t=1643714542_2b529cda80e6fc9906968ea2153518d885aa9529 [following]
--2022-02-01 12:17:23--  https://d28dx6y1hfq314.cloudfront.net/1632/11441/debian/package_files/3261921.deb?t=1643714542_2b529cda80e6fc9906968ea2153518d885aa9529
Resolving d28dx6y1hfq314.cloudfront.net (d28dx6y1hfq314.cloudfront.net)... 52.222.196.155, 52.222.196.151, 52.222.196.119, ...
Connecting to d28dx6y1hfq314.cloudfront.net (d28dx6y1hfq314.cloudfront.net)|52.222.196.155|:443... connected._


And it's freezing here. I'd tried another wget and working fine :

_root@DIGPRHOMER01:~/homer-installer# wget -O python_fn.vim http://www.vim.org/scripts/download_script.php?src_id=9196
--2022-02-01 12:21:02--  http://www.vim.org/scripts/download_script.php?src_id=9196
Resolving www.vim.org (www.vim.org)... 44.237.4.221
Connecting to www.vim.org (www.vim.org)|44.237.4.221|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://www.vim.org/scripts/download_script.php?src_id=9196 [following]
--2022-02-01 12:21:03--  https://www.vim.org/scripts/download_script.php?src_id=9196
Connecting to www.vim.org (www.vim.org)|44.237.4.221|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/octetstream]
Saving to: 'python_fn.vim'

python_fn.vim                                                   [ <=>                                                                                                                                       ]  12.42K  --.-KB/s    in 0s

2022-02-01 12:21:04 (145 MB/s) - 'python_fn.vim' saved [12723]_

**Comment by chabeaumont** [comment]
Found the problem. It was an (strange) issue wih my firewall. Working great now. Thanks for your times and your helps.
