### ISSUE TITLE
Unable to Install Homer on Ubuntu 22.04

### ISSUE THREAD

**Issue by olaotanedagbami** [sipcapture/homer-installer#85]
Hello please I am trying to install Homer 7 on my Ubuntu 22.04 server using both the quick install  method but this is the error i got 
ERROR: Sorry, this Installer does not support your OS yet! Please follow instructions in the HOW-TO for manual installation & setup available at http://sipcapture.org

I tried the manual method which requires i install heplify and I got this E: Unable to locate package heplify

The manual method ran on 18.04. please I need to know what to do, Is there no support for Ubuntu 22.04?
Please help

**Comment by lmangani** [comment]
Hello @olaotanedagbami 
Our packages are all almost identical (static binaries) but OSes like to make this quite hard with versions.

Our repository supports Debian stretch, buster, bullseye, Ubuntu focal and bionic, and RHEL 7/8.

You can either force a repository from a previous version or use the debian equivalent until we expand it.
