### ISSUE TITLE
No data available on homer [fresh installs]

### ISSUE THREAD

**Issue by ewadii** [sipcapture/homer-installer#88]
Hello, 
No communication problem between my opensips box and heplify server.
After a reboot, No data is available on Homer GUI ,  this is the only error message i see : 

"Jan 03 11:27:21 homer heplify-server[586]: dial tcp 127.0.0.1:5432: connect: connection refused"

A systemctl restart heplify-server solves the problem.

I've tested this on both distributions and different versions [Debian 9 - 10 - 11] & Centos [7 - 8]

I am using DigitalOcean droplets.

**Comment by lmangani** [comment]
> "Jan 03 11:27:21 homer heplify-server[586]: dial tcp 127.0.0.1:5432: connect: connection refused"

This seems a database issue and if so, unrelated to homer/heplify-server. Are you saying it does not automatically reconnect?
Is postgres really up when this error was happening? Services should be started in the right order.

**Comment by ewadii** [comment]
Hello , I havent configured postegres myself. First and only thing i'm running after an apt update/upgrade is the Bash Installer script.
And yes it does not automatically reconnect. My OpenSIPS keeps sending sip signals, but nothing is displayed on Homer GUI.

**Comment by ewadii** [comment]
Ok i had to enable After=network.target postgresql.service on /lib/systemd/system/heplify-server.service.
I think it would be cool to add that to the documentation for those having Postgresql on the same host.
Thank you.
