### ISSUE TITLE
update Telegraf GPG key

### ISSUE THREAD

**Issue by EvilBob01** [sipcapture/homer-installer#91]
Had some trouble with the install. The Telegraf GPG key is invalid and the homer-installer fails. I followed the directions here to replace the GPG key:
https://github.com/influxdata/telegraf/blob/master/README.md#package-repository
before running ./homer_installer.sh and it made all the difference.

**Comment by lmangani** [comment]
Fixed by @mentax007 https://github.com/sipcapture/homer-installer/pull/89
